### ISSUE TITLE
No valid licenses found for TC_PYTHON

### ISSUE THREAD

**Issue by yiz-yang** [Y-Matsuoka-Material/GBseg-TCPython#1]
Hello, may I ask that there is a problem that I do not have a valid license when I use the education edition? Is it because the education edition does not have a license? (No valid licenses found for TC_PYTHON)

**Comment by Y-Matsuoka-Material** [comment]
Hi 2433470100, this program requires [TC-Python](https://thermocalc.com/products/software-development-kits/tc-python/) which requires dedicated license to use.
I have not used [Thermo-Calc's educational package](https://thermocalc.com/academia/free-educational-package/), but I suspect the problem is that Thermo-Calc's educational package does not include a license for TC-Python.

**Comment by yiz-yang** [comment]
Yes, I have a feeling that this education version of the license does not connect to tc-python. thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月27日(星期一) 中午12:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Y-Matsuoka-Material/GBseg-TCPython] No valid licenses found for TC_PYTHON (Issue #1)





 
Hi 2433470100, this program requires TC-Python which requires dedicated license to use.
 I have not used Thermo-Calc's educational package, but I suspect the problem is that Thermo-Calc's educational package does not include a license for TC-Python.
